;
; File generated by cc65 v 2.19 - Git 2ea1df8b2
;
	.fopt		compiler,"cc65 v 2.19 - Git 2ea1df8b2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_set_irq
	.export		_int_stack
	.export		_count
	.export		_time
	.export		_foo
	.export		_main

.segment	"BSS"

_int_stack:
	.res	64,$00
_count:
	.res	2,$00
_time:
	.res	4,$00

; ---------------------------------------------------------------
; unsigned char __near__ foo (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_foo: near

.segment	"CODE"

	ldx     #$00
	lda     $A04C
	and     #$7F
	sta     $A04C
	inc     _count
	bne     L0002
	inc     _count+1
L0002:	ldx     #$00
	lda     _count
	sta     $A004
	ldx     #$00
	lda     $A04C
	ora     #$08
	sta     $A04C
	ldx     #$00
	lda     #$01
	jmp     L0001
L0001:	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	sei
	lda     #$02
	sta     sreg+1
	lda     #$FA
	sta     sreg
	lda     #$80
	ldx     #$F0
	sta     _time
	stx     _time+1
	ldy     sreg
	sty     _time+2
	ldy     sreg+1
	sty     _time+3
	lda     #<(_foo)
	ldx     #>(_foo)
	jsr     pushax
	lda     #<(_int_stack)
	ldx     #>(_int_stack)
	jsr     pushax
	ldx     #$00
	lda     #$40
	jsr     _set_irq
	ldx     #$00
	lda     #$00
	sta     _count
	stx     _count+1
	ldx     #$00
	lda     _count
	sta     $A004
	lda     _time+3
	sta     sreg+1
	lda     _time+2
	sta     sreg
	ldx     _time+1
	lda     _time
	sta     $A048
	stx     $A048+1
	ldy     sreg
	sty     $A048+2
	ldy     sreg+1
	sty     $A048+3
	ldx     #$00
	lda     $A04C
	ora     #$0B
	sta     $A04C
	cli
	jmp     L0002
L0002:	jmp     L0002
	rts

.endproc

